/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SectionA;

/**
 *
 * @author Examiner
 */
public class Question1_2 extends javax.swing.JFrame {

    /**
     * Creates new form Question1_2
     */
    public Question1_2() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("ESTATE AGENT COMMISSION");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txfPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rBtnCash = new javax.swing.JRadioButton();
        rBtnCredit = new javax.swing.JRadioButton();
        btnCalcCommission = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaOuput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SectionA/picture.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 320, 130));

        jLabel1.setText("ENTER PRICE OF HOUSE: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, -1));
        jPanel1.add(txfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 120, -1));

        jLabel3.setText("SELECT PAYMENT OPTION:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 190, -1));

        buttonGroup1.add(rBtnCash);
        rBtnCash.setText("CASH");
        jPanel1.add(rBtnCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        buttonGroup1.add(rBtnCredit);
        rBtnCredit.setText("CREDIT (BOND)");
        jPanel1.add(rBtnCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        btnCalcCommission.setText("CALCULATE COMMISSION");
        jPanel1.add(btnCalcCommission, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 430, -1));

        txaOuput.setColumns(20);
        txaOuput.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txaOuput.setRows(5);
        jScrollPane1.setViewportView(txaOuput);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 430, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question1_2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcCommission;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rBtnCash;
    private javax.swing.JRadioButton rBtnCredit;
    private javax.swing.JTextArea txaOuput;
    private javax.swing.JTextField txfPrice;
    // End of variables declaration//GEN-END:variables
}
